package:
  name: conda-offline-channel
  version: {{ GIT_DESCRIBE_TAG }}

source:
  #git_url: ../
  path: ../

build:
  # number: 0
  entry_points:
    - conda-offline-channel = conda_offline_channel.cli.main_offline_channel:main

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python
    - conda >=4.3.0
    - conda-build >=3.0.0
    - typing # [py27 or py34]

test:
  commands:
    - which conda-offline-channel  # [unix]
    - where conda-offline-channel  # [win]
    - conda offline-channel -h
    - conda --help
  
  imports:
    - conda_offline_channel

about:
  home: https://github.com/lambdalisue/conda-offline-channel
  license: MIT License
  summary: 'Build an offline conda channel which contains all requirements'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
